### ISSUE TITLE
Your code is not user friendly for beginner..

### ISSUE THREAD

**Issue by raviji** [awslabs/aws-cognito-angular2-quickstart#73]
Need more information about userpool with angular step by step.

**Comment by vbudilov** [comment]
What information, that's not already available, would you like to see?

**Comment by raviji** [comment]
@vbudilov Your project is working fine with your code but I have angular 4 app or angular 2 app, how to use this aws cognito to my project?.

Request: Need more simple steps  to implement AWS with any app.

**Comment by vbudilov** [comment]
Take a look at my last comment here: https://github.com/awslabs/aws-cognito-angular2-quickstart/issues/66

**Comment by raviji** [comment]
@vbudilov thanks for that...

I saw this `https://github.com/aws/amazon-cognito-identity-js` already but i am expecting for angular 4 app because you have already done with angular 2. 

Thats fine am working with angular 4 app with aws, and i will make a git repo for public with full step by step doc to understand even beginner asap.

**Comment by vbudilov** [comment]
I've upgraded this code to angular4 a while back: "@angular/core": "4.0.0"

**Comment by raviji** [comment]
@vbudilov Thank you....

**Comment by codercodingthecode** [comment]
I wish cognito implementation was more clear, It could be as simple as google cloud login/register.  But aws cognito and a bunch of its docs are just disengaged per se. This is not friendly at all. It shouldn't require so many stuff all over the place. The (one) aws-sdk should suffice since you can import only the things you need. I guess I will have to go another route with observables to get around this cognito implementation mess. I'm not hardly criticizing your implementation. But I guess, that's what aws came down to.

**Comment by kwalski** [comment]
agree with @andythedandyone, if cognito can't save developer's time, then what's the point
